services:
  - type: web
    name: portfolio-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Kushal Portfolio API
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_TIMEZONE
        value: Asia/Kathmandu
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: log
      - key: SANCTUM_EXPIRATION
        value: "1440"
      - key: SEED_INITIAL_DATA
        value: "true"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FRONTEND_URLS
        sync: false
      - key: DB_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
